name: ${project.artifactId}
version: ${project.version}
description: ${plugin-description}
author: ${plugin-author}
database: false
main: ru.dpohvar.varscript.VarScript
softdepend: [PowerNBT]

commands:
  script:
    description: run line
    aliases: ['>', g>]
    usage: /> {groovy script ...} | scriptName [arg1[,arg2 ...[,argN]]]
    permission: varscript.run
  workspace:
    description: manage workspaces
    aliases: [workspaces, ws]
    usage: see /ws help
    permission: varscript.workspace
